Repository boostcampwm-2022/android11-almost-there, pull requests merged in 2022-11, with the labels that each got.

#11 📝 docs: PR template 수정
  .github/pull_request_template.md
Labels: 📝 문서

#16 Feature/splash/make splash
  app/build.gradle
  app/src/debug/res/drawable/image_dog.png
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/ui/FindPromiseFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/MainActivity.kt
  app/src/main/kotlin/com/woory/almostthere/ui/MainFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/dummy/DummyAlmostPromise.kt
  app/src/main/kotlin/com/woory/almostthere/ui/dummy/DummyCreatePromiseFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/dummy/DummyEndedPromise.kt
  app/src/main/kotlin/com/woory/almostthere/ui/dummy/DummyJoinFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/splash/SplashActivity.kt
  app/src/main/kotlin/com/woory/almostthere/util/Utils.kt
  app/src/main/res/anim/slide_in_from_down.xml
  app/src/main/res/anim/slide_in_from_left.xml
  app/src/main/res/anim/slide_in_from_right.xml
  app/src/main/res/anim/slide_in_from_up.xml
  app/src/main/res/anim/slide_out_to_down.xml
  app/src/main/res/anim/slide_out_to_left.xml
  app/src/main/res/anim/slide_out_to_right.xml
  app/src/main/res/anim/slide_out_to_up.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_dummy_almost_promise.xml
  app/src/main/res/layout/fragment_dummy_create_promise.xml
  app/src/main/res/layout/fragment_dummy_ended_promise.xml
  app/src/main/res/layout/fragment_dummy_join.xml
  app/src/main/res/layout/fragment_find_promise.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/navigation/almost_there_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🔨 기능

#17 약속 생성 화면으로 이동 및 약속 데이터 입력 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/model/DateUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/LocationUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/PromiseInfoUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/TimeUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/UserState.kt
  app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseActivity.kt
  app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseViewModel.kt
  app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/LocationSearchFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/dummy/DummyCreatePromiseFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_hourglass.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_time.xml
  app/src/main/res/drawable/ic_today.xml
  app/src/main/res/layout/activity_creating_promise.xml
  app/src/main/res/layout/fragment_creating_promise.xml
  app/src/main/res/layout/fragment_dummy_create_promise.xml
  app/src/main/res/layout/fragment_location_search.xml
  app/src/main/res/layout/layout_game_time_picker_dialog.xml
  app/src/main/res/navigation/almost_there_nav.xml
  app/src/main/res/navigation/nav_creating_promise.xml
  app/src/main/res/values/strings.xml
Labels: 🔨 기능

#23 게임 진행 ui 일부 구현
  app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/LocationSearchFragment.kt
  app/src/main/kotlin/com/woory/almostthere/ui/customview/HPBar.kt
  app/src/main/kotlin/com/woory/almostthere/ui/gaming/GamingFragment.kt
  app/src/main/kotlin/com/woory/almostthere/util/Constants.kt
  app/src/main/res/drawable/bg_btn_of_map.xml
  app/src/main/res/drawable/bg_character_img.xml
  app/src/main/res/drawable/bg_hp_bar.xml
  app/src/main/res/drawable/bg_ranking.xml
  app/src/main/res/drawable/ic_baseline_location_searching.xml
  app/src/main/res/drawable/ic_baseline_timer.xml
  app/src/main/res/drawable/ic_outline_info.xml
  app/src/main/res/layout/activity_gaming.xml
  app/src/main/res/layout/customview_hp_bar.xml
  app/src/main/res/layout/fragment_find_promise.xml
  app/src/main/res/layout/fragment_gaming.xml
  app/src/main/res/layout/item_real_time_ranking.xml
  app/src/main/res/layout/layout_character_img.xml
  app/src/main/res/layout/layout_map_icon_info.xml
  app/src/main/res/layout/layout_map_icon_location.xml
  app/src/main/res/values/attrs_hp_bar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🔨 기능

#40 초대 코드 입력 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/binding/BindingAdapter.kt
  app/src/main/kotlin/com/woory/almostthere/initializer/TimberInitializer.kt
  app/src/main/kotlin/com/woory/almostthere/model/PromiseUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/mapper/PromiseUiStateMapper.kt
  app/src/main/kotlin/com/woory/almostthere/model/mapper/UiStateMapper.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/CodeState.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/FormState.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/JoinActivity.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/JoinViewModel.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/ProfileActivity.kt
  app/src/main/kotlin/com/woory/almostthere/util/InviteCodeUtil.kt
  app/src/main/res/drawable/ic_invite_code.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/kotlin/com/woory/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/woory/data/model/Promise.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/RemoteDataStore.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultRemoteDataStore.kt
  firebase/src/main/kotlin/com/woory/firebase/di/FirebaseModule.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/ModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/PromiseModel.kt
Labels: 🔨 기능

#41 초대 코드 입력 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/binding/BindingAdapter.kt
  app/src/main/kotlin/com/woory/almostthere/initializer/TimberInitializer.kt
  app/src/main/kotlin/com/woory/almostthere/model/PromiseUiState.kt
  app/src/main/kotlin/com/woory/almostthere/model/mapper/PromiseUiStateMapper.kt
  app/src/main/kotlin/com/woory/almostthere/model/mapper/UiStateMapper.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/CodeState.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/FormState.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/JoinActivity.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/JoinViewModel.kt
  app/src/main/kotlin/com/woory/almostthere/ui/join/ProfileActivity.kt
  app/src/main/kotlin/com/woory/almostthere/util/InviteCodeUtil.kt
  app/src/main/res/drawable/ic_invite_code.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/kotlin/com/woory/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/woory/data/model/Promise.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/RemoteDataStore.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultRemoteDataStore.kt
  firebase/src/main/kotlin/com/woory/firebase/di/FirebaseModule.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/ModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/PromiseModel.kt
Labels: 🔨 기능

#49 파이어베이스 약속 저장 관련 코드 수정
  data/src/main/kotlin/com/woory/data/model/PromiseDataModel.kt
  data/src/main/kotlin/com/woory/data/model/UserStateModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserHpMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserStateMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/PromiseData.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserHpDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocation.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocationDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/util/InviteCodeUtil.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/PromiseDataModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyAlmostPromise.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyEndedPromise.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyJoinFragment.kt
  presentation/src/main/res/layout/fragment_dummy_almost_promise.xml
  presentation/src/main/res/layout/fragment_dummy_ended_promise.xml
  presentation/src/main/res/layout/fragment_dummy_join.xml
  presentation/src/main/res/navigation/nav_main.xml
Labels: 🌟 리팩토링

#50 파이어베이스 data class 수정
  data/src/main/kotlin/com/woory/data/model/PromiseDataModel.kt
  data/src/main/kotlin/com/woory/data/model/UserStateModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserHpMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserStateMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/PromiseData.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserHpDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocation.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocationDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/util/InviteCodeUtil.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/PromiseDataModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyAlmostPromise.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyEndedPromise.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/dummy/DummyJoinFragment.kt
  presentation/src/main/res/layout/fragment_dummy_almost_promise.xml
  presentation/src/main/res/layout/fragment_dummy_ended_promise.xml
  presentation/src/main/res/layout/fragment_dummy_join.xml
  presentation/src/main/res/navigation/nav_main.xml
Labels: 🌟 리팩토링

#52 프로필 입력 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/initializer/ThreeTenInitializer.kt
  data/src/main/kotlin/com/woory/data/model/UserModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/DatabaseDataSource.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  database/src/main/kotlin/com/woory/database/PromiseDao.kt
  database/src/main/kotlin/com/woory/database/datasource/DefaultDatabaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/model/Color.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/UserMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileImage.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileModule.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Utils.kt
  presentation/src/main/res/drawable/bg_profile.xml
  presentation/src/main/res/drawable/ic_nickname.xml
  presentation/src/main/res/drawable/ic_switch.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#54 프로필 입력 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/initializer/ThreeTenInitializer.kt
  data/src/main/kotlin/com/woory/data/model/UserModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/DatabaseDataSource.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  database/src/main/kotlin/com/woory/database/PromiseDao.kt
  database/src/main/kotlin/com/woory/database/datasource/DefaultDatabaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/model/Color.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/UserMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileImage.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileModule.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Utils.kt
  presentation/src/main/res/drawable/bg_profile.xml
  presentation/src/main/res/drawable/ic_nickname.xml
  presentation/src/main/res/drawable/ic_switch.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#57 약속 상세화면 구현 및 각자 작업물 통합
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/ModelMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  network/src/main/AndroidManifest.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseUiState.kt
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/layout/activity_promise_info.xml
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그, 🔨 기능

#60 약속 상세화면 추가 구현
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseUserAdapter.kt
  presentation/src/main/res/drawable/ic_crown.xml
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#64 약속 생성 맵 화면 구현 및 에러 수정
  data/src/main/kotlin/com/woory/data/model/LocationSearchModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/NetworkDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserHpMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  network/src/main/kotlin/com/woory/network/DefaultNetworkDataSource.kt
  network/src/main/kotlin/com/woory/network/TMapService.kt
  network/src/main/kotlin/com/woory/network/model/LocationSearchResponse.kt
  network/src/main/kotlin/com/woory/network/model/Response.kt
  network/src/main/kotlin/com/woory/network/model/mapper/LocationSearchMapper.kt
  network/src/main/kotlin/com/woory/network/model/mapper/ModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/UserMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/searchlocation/SearchResultMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResult.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResultAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseUiState.kt
  presentation/src/main/res/layout/fragment_location_search.xml
  presentation/src/main/res/layout/fragment_location_search_result.xml
  presentation/src/main/res/layout/item_location_search_result.xml
  presentation/src/main/res/navigation/nav_creating_promise.xml
  presentation/src/main/res/values/strings.xml
Labels: 🌟 리팩토링

#66 Hilt MapView 버그 수정, 약속 생성 및 참여 디자인 수정, 약속 생성 시 프로필 받기
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/di/ProfileModule.kt
  presentation/src/main/kotlin/com/woory/presentation/model/ProfileImage.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/ProfileFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ActivityContext.kt
  presentation/src/main/res/layout/activity_join.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_creating_promise.xml
  presentation/src/main/res/layout/fragment_gaming.xml
  presentation/src/main/res/layout/fragment_location_search.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/layout/layout_game_time_picker_dialog.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#67 Hilt MapView 버그 수정, 약속 생성 및 참여 디자인 수정, 약속 생성 시 프로필 받기
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/di/ProfileModule.kt
  presentation/src/main/kotlin/com/woory/presentation/model/ProfileImage.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/ProfileFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ActivityContext.kt
  presentation/src/main/res/layout/activity_join.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/fragment_creating_promise.xml
  presentation/src/main/res/layout/fragment_gaming.xml
  presentation/src/main/res/layout/fragment_location_search.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/layout/layout_game_time_picker_dialog.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#71 약속 준비 및 시작 알람 등록 및 Notification 알림
  app/src/main/AndroidManifest.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmTouchReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationChannelProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/util/Extensions.kt
  presentation/src/main/kotlin/com/woory/presentation/model/AlarmState.kt
  presentation/src/main/kotlin/com/woory/presentation/model/PromiseAlarm.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/alarm/PromiseAlarmMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Constants.kt
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#73 유저 식별 key 구현
  data/build.gradle.kts
  data/src/main/kotlin/com/woory/data/di/DataStoreModule.kt
  data/src/main/kotlin/com/woory/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/woory/data/model/UserPreferencesModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultUserRepository.kt
  data/src/main/kotlin/com/woory/data/repository/UserRepository.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
Labels: 🔨 기능

#74 유저 식별 key 구현
  data/build.gradle.kts
  data/src/main/kotlin/com/woory/data/di/DataStoreModule.kt
  data/src/main/kotlin/com/woory/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/woory/data/model/UserPreferencesModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultUserRepository.kt
  data/src/main/kotlin/com/woory/data/repository/UserRepository.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
Labels: 🔨 기능

#75 약속 상세화면 리팩토링 및 뒤로가기 기능 구현
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserHpMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseUiState.kt
  presentation/src/main/res/drawable/ic_refresh.xml
  presentation/src/main/res/layout/fragment_location_search_result.xml
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그, 🌟 리팩토링

#80 약속 생성 시 날짜 버그 해결 및 날짜 사용 코드 리팩토링
  database/src/main/kotlin/com/woory/database/util/TimeConverter.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/util/TimeConverter.kt
  network/build.gradle.kts
  network/src/main/kotlin/com/woory/network/util/TimeConverter.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/util/Extensions.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResult.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResultAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Constants.kt
  presentation/src/main/kotlin/com/woory/presentation/util/TimeConverter.kt
Labels: 🐞 버그, 🌟 리팩토링

#82 재부팅 시 AlarmManager 알람 재등록 기능 구현
  app/src/main/AndroidManifest.xml
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/DatabaseDataSource.kt
  database/src/main/kotlin/com/woory/database/OffsetDateTimeConverters.kt
  database/src/main/kotlin/com/woory/database/PromiseAlarmDao.kt
  database/src/main/kotlin/com/woory/database/datasource/DefaultDatabaseDataSource.kt
  database/src/main/kotlin/com/woory/database/mapper/PromiseAlarmMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/HiltBroadcastReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmRestartReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmTouchReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/util/Extensions.kt
  presentation/src/main/kotlin/com/woory/presentation/model/AlarmState.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/alarm/PromiseAlarmMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
Labels: 🔨 기능

#84 Android12 관련 Notification 수정
  database/src/main/kotlin/com/woory/database/OffsetDateTimeConverters.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmRestartReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmTouchReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/util/Extensions.kt
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능, 🌟 리팩토링

#87 BroadcastReceiver에서 처리하던 작업들 Service로 이전
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmRestartReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmTouchReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationChannelProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/receiver/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/receiver/AlarmTouchReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/receiver/BootBroadcastReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/AlarmRestartService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseAlarmRegisterService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseReadyService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/util/Extensions.kt
  presentation/src/main/res/values/strings.xml
Labels: 🌟 리팩토링

#88 게임 결과 화면 ui 구현
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/CalculateFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserPaymentAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserRankingAdapter.kt
  presentation/src/main/res/drawable/bg_sudden_shiba.xml
  presentation/src/main/res/layout/activity_game_result.xml
  presentation/src/main/res/layout/dialog_amount_due.xml
  presentation/src/main/res/layout/fragment_calculate.xml
  presentation/src/main/res/layout/fragment_find_promise.xml
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_gaming.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/layout/item_real_time_ranking.xml
  presentation/src/main/res/layout/item_user_payment.xml
  presentation/src/main/res/layout/layout_character_img.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/navigation/nav_game_result.xml
  presentation/src/main/res/raw/beer.json
  presentation/src/main/res/raw/money.json
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: 🔨 기능

#89 게임 결과 화면 ui 구현
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/CalculateFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserPaymentAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserRankingAdapter.kt
  presentation/src/main/res/drawable/bg_sudden_shiba.xml
  presentation/src/main/res/layout/activity_game_result.xml
  presentation/src/main/res/layout/dialog_amount_due.xml
  presentation/src/main/res/layout/fragment_calculate.xml
  presentation/src/main/res/layout/fragment_find_promise.xml
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_gaming.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/layout/item_real_time_ranking.xml
  presentation/src/main/res/layout/item_user_payment.xml
  presentation/src/main/res/layout/layout_character_img.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/navigation/nav_game_result.xml
  presentation/src/main/res/raw/beer.json
  presentation/src/main/res/raw/money.json
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: 🔨 기능

#92 게임 화면 유저 위치 정보, 자기장 정보 띄우기 구현
  data/src/main/kotlin/com/woory/data/model/MagneticInfoModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/MagneticDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/MagneticInfoDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocationDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/util/TimeConverter.kt
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/model/Location.kt
  presentation/src/main/kotlin/com/woory/presentation/model/MagneticInfo.kt
  presentation/src/main/kotlin/com/woory/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/UiModelMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/location/UserLocationMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/magnetic/MagneticInfoMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/user/UserHpMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/util/DistanceUtil.kt
  presentation/src/main/res/layout/fragment_location_search.xml
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능
