Repository boostcampwm-2022/android11-almost-there, pull requests merged in 2022-12, with the labels that each got.

#94 약속 히스토리 화면 구현
  build.gradle.kts
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/di/PromiseHistoryModule.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/RankBadge.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryType.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/RankBadgeType.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/main/FindPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/main/MainFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ViewExtension.kt
  presentation/src/main/res/layout/activity_promise_history.xml
  presentation/src/main/res/layout/item_promise_before.xml
  presentation/src/main/res/layout/item_promise_end.xml
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/layout/item_promise_ongoing.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: 🔨 기능

#95 약속 히스토리 화면 구현
  build.gradle.kts
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/di/PromiseHistoryModule.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/RankBadge.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryType.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/RankBadgeType.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/main/FindPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/main/MainFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promises/PromisesViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ViewExtension.kt
  presentation/src/main/res/layout/activity_promise_history.xml
  presentation/src/main/res/layout/item_promise_before.xml
  presentation/src/main/res/layout/item_promise_end.xml
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/layout/item_promise_ongoing.xml
  presentation/src/main/res/navigation/nav_main.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
Labels: 🔨 기능

#96 게임 준비 알람 터치 관련 기능 구현
  data/src/main/kotlin/com/woory/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/woory/data/model/PathModel.kt
  data/src/main/kotlin/com/woory/data/model/RouteType.kt
  data/src/main/kotlin/com/woory/data/model/UserStateModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultRouteRepository.kt
  data/src/main/kotlin/com/woory/data/repository/RouteRepository.kt
  data/src/main/kotlin/com/woory/data/source/NetworkDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/UserLocationMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/UserLocationDocument.kt
  network/build.gradle.kts
  network/src/main/kotlin/com/woory/network/DefaultNetworkDataSource.kt
  network/src/main/kotlin/com/woory/network/ODsayService.kt
  network/src/main/kotlin/com/woory/network/TMapService.kt
  network/src/main/kotlin/com/woory/network/di/NetworkModule.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseReadyService.kt
  presentation/src/main/kotlin/com/woory/presentation/model/Location.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/location/UserLocationMapper.kt
Labels: 🔨 기능

#101 게임 결과 화면 로직 구현
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/presentation/model/user/gameresult/UserRanking.kt
  presentation/src/main/kotlin/com/woory/presentation/model/user/gameresult/UserSplitMoneyItem.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/BaseDialogFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/BaseViewHolder.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyLogic.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/TotalCostFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserPaymentAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserSplitMoneyAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Utils.kt
  presentation/src/main/res/layout/dialog_fragment_total_cost.xml
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/item_balance.xml
  presentation/src/main/res/layout/item_user_split_money.xml
  presentation/src/main/res/layout/layout_progressbar.xml
  presentation/src/main/res/navigation/nav_game_result.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/test/java/com/woory/presentation/ExampleUnitTest.kt
  presentation/src/test/java/com/woory/presentation/ui/gameresult/SplitMoneyLogicTest.kt
Labels: 🔨 기능

#103 약속 히스토리 화면 디테일 수정
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/TextViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/TimeUtils.kt
  presentation/src/main/res/layout/activity_join.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/activity_promise_history.xml
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#109 도착 감지 및 Shake 하여 도착 알림 기능 구현
  app/src/main/AndroidManifest.xml
  data/src/main/kotlin/com/woory/data/model/AddedUserHpModel.kt
  data/src/main/kotlin/com/woory/data/model/MagneticInfoModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultRouteRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/AddedUserHpMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/MagneticDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/PromiseDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/AddedUserHpDocument.kt
  firebase/src/main/kotlin/com/woory/firebase/model/MagneticInfoDocument.kt
  network/src/main/kotlin/com/woory/network/DefaultNetworkDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/model/AddedUserHp.kt
  presentation/src/main/kotlin/com/woory/presentation/model/MagneticInfo.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/gaming/BottomSheetProfile.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/magnetic/MagneticInfoMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/user/AddedUserHpMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/LocationSearchResultAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserRankingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/ShakeDeviceFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/ShakeEventListener.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Constants.kt
  presentation/src/main/kotlin/com/woory/presentation/util/DistanceUtil.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Exceptions.kt
  presentation/src/main/kotlin/com/woory/presentation/util/Utils.kt
  presentation/src/main/res/layout/bottomsheet_gaming.xml
  presentation/src/main/res/layout/dialog_fragment_shake_device.xml
  presentation/src/main/res/layout/fragment_gaming.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/raw/shake_device.json
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#111 게임 화면 유저 마커 제작 및 실시간 순위 로직 추가
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingViewModel.kt
  presentation/src/main/res/drawable/bg_speech_bubble_body.xml
  presentation/src/main/res/drawable/bg_speech_bubble_tail.xml
  presentation/src/main/res/layout/customview_charater_marker.xml
Labels: 🔨 기능

#116 Pending Intent 등록 전 이전 PendingIntent 취소 후 등록 / Service Notification 재실행 방지
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
Labels: 🐞 버그, 🌟 리팩토링

#118 :bug: fix: 약속 참여시 알람 등록되도록 수정
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
Labels: 🐞 버그

#135 게임 결과 화면에서 Firebase에서 불러오는 로직 추가 및 정산 로직 UI 개선
  data/src/main/kotlin/com/woory/data/model/UserRankingModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/user/UserRankingMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/layout_submit_button.xml
Labels: 🔨 기능

#136 게임 결과 화면에서 Firebase에서 불러오는 로직 추가 및 정산 로직 UI 개선
  data/src/main/kotlin/com/woory/data/model/UserRankingModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/user/UserRankingMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/layout_submit_button.xml
Labels: 🔨 기능

#138 게임 결과 화면 UI 보완 및 button layout 사용 버그 수정
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/binding/TextViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeDecoration.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeScrollListener.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserRankingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/util/KonfettiPresets.kt
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/layout/layout_submit_button.xml
  presentation/src/main/res/values/dimens.xml
Labels: 🔨 기능

#139 게임 결과 화면 UI 보완 및 button layout 사용 버그 수정
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/binding/TextViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeDecoration.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeScrollListener.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/UserRankingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/util/KonfettiPresets.kt
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/layout/layout_submit_button.xml
  presentation/src/main/res/values/dimens.xml
Labels: 🐞 버그, 🔨 기능

#141 다크모드 대응 및 status bar 투명하게 변경, toolbar에 bind:title하는 코드 삭제
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/res/layout/activity_game_result.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그, 🌟 리팩토링

#142 초대 코드, 프로필 입력 화면 버그 수정, 리팩토링
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ButtonBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ImageViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/TextInputLayoutBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/extension/LifecycleExtension.kt
  presentation/src/main/kotlin/com/woory/presentation/model/UiState.kt
  presentation/src/main/kotlin/com/woory/presentation/model/exception/AlmostThereException.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/BaseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/InviteCodeUtil.kt
  presentation/src/main/kotlin/com/woory/presentation/util/SoftKeyboardUtils.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ViewUtils.kt
  presentation/src/main/kotlin/com/woory/presentation/util/flow/EventFlow.kt
  presentation/src/main/res/layout/activity_game_result.xml
  presentation/src/main/res/layout/activity_join.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#143 초대 코드, 프로필 입력 화면 버그 수정, 리팩토링
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ButtonBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ImageViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/TextInputLayoutBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/extension/LifecycleExtension.kt
  presentation/src/main/kotlin/com/woory/presentation/model/UiState.kt
  presentation/src/main/kotlin/com/woory/presentation/model/exception/AlmostThereException.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/BaseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/JoinViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/InviteCodeUtil.kt
  presentation/src/main/kotlin/com/woory/presentation/util/SoftKeyboardUtils.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ViewUtils.kt
  presentation/src/main/kotlin/com/woory/presentation/util/flow/EventFlow.kt
  presentation/src/main/res/layout/activity_game_result.xml
  presentation/src/main/res/layout/activity_join.xml
  presentation/src/main/res/layout/activity_profile.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#147 게임 결과 화면 UI 개선
  network/src/test/kotlin/com/woory/network/NetworkDataSourceUnitTest.kt
  network/src/test/kotlin/com/woory/network/fake/FakeNetworkDataSource.kt
  network/src/test/kotlin/com/woory/network/fake/FakeNetworkModule.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoActivity.kt
  presentation/src/main/res/drawable/bg_game_result.xml
  presentation/src/main/res/layout/dialog_fragment_total_cost.xml
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/fragment_split_money.xml
  presentation/src/main/res/layout/item_ranking.xml
  presentation/src/main/res/layout/item_user_split_money.xml
  presentation/src/main/res/layout/layout_double_button.xml
  presentation/src/main/res/layout/layout_progressbar.xml
  presentation/src/main/res/layout/layout_submit_button.xml
  presentation/src/main/res/raw/finish.json
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그, 🌟 리팩토링

#148 게임 진행 관련 예외처리 하기, 게임 상세 화면 준비 버튼 만들기
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/background/receiver/AlarmReceiver.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/AlarmRestartService.kt
  presentation/src/main/kotlin/com/woory/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseUserAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/ReadyStatus.kt
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 기능

#151 게임 결과 화면 버그 수정 및 디자인 수정
  presentation/src/main/res/layout/dialog_fragment_total_cost.xml
  presentation/src/main/res/layout/fragment_game_result.xml
  presentation/src/main/res/layout/layout_toolbar.xml
Labels: 🐞 버그

#153 위치 수집 에러 해결 및 약속 생성 디자인 수정
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/res/layout/fragment_creating_promise.xml
Labels: 🐞 버그

#164 약속 상세 화면 버그 등 해결
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/res/layout/item_promise_user.xml
Labels: 🐞 버그

#167 BottomSheet 글자깨짐 해결, toolbar 다크모드 대응, 약속 생성 시 버그 해결, 기타 버그 해결
  presentation/src/main/kotlin/com/woory/presentation/model/Color.kt
  presentation/src/main/kotlin/com/woory/presentation/model/exception/CreatingPromiseException.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ResourceManager.kt
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/drawable/ic_time.xml
  presentation/src/main/res/layout/bottomsheet_gaming.xml
  presentation/src/main/res/layout/bottomsheet_gaming_promise_info.xml
  presentation/src/main/res/layout/layout_character_img.xml
  presentation/src/main/res/layout/layout_toolbar.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그

#168 게임 화면 에러 수정
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/model/gaming/UserRanking.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingRankingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingViewModel.kt
  presentation/src/main/res/layout/item_gaming_ranking.xml
Labels: 🐞 버그, 🌟 리팩토링

#169 게임 진행 화면 BottomSheet margin 옆에 추가
  presentation/src/main/res/layout/bottomsheet_gaming_promise_info.xml
Labels: 🐞 버그

#185 약속 정보 화면 관련 버그 수정
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/res/layout/fragment_promise_info.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그

#187 약속 생성 화면 UX/UI 개선 및 게임 진행에 마커 디자인 수정, BottomSheet 버그 수정
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CheckPromiseDataDialog.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/util/TimeUtils.kt
  presentation/src/main/res/drawable/bg_speech_bubble_body.xml
  presentation/src/main/res/drawable/ic_calendar.xml
  presentation/src/main/res/drawable/ic_hourglass.xml
  presentation/src/main/res/layout/bottomsheet_gaming.xml
  presentation/src/main/res/layout/customview_character_marker.xml
  presentation/src/main/res/layout/customview_charater_marker.xml
  presentation/src/main/res/layout/dialog_fragment_check_promise_data.xml
  presentation/src/main/res/layout/fragment_creating_promise.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/layout_game_time_picker_dialog.xml
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#188 게임 진행 화면 에러 해결
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/model/MagneticInfoDocument.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingViewModel.kt
Labels: 🐞 버그, 🌟 리팩토링

#194 약속 히스토리 리팩토링
  build.gradle.kts
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/DatabaseDataSource.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  database/src/main/kotlin/com/woory/database/PromiseAlarmDao.kt
  database/src/main/kotlin/com/woory/database/datasource/DefaultDatabaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/RankBadge.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/res/drawable/ic_destination.xml
  presentation/src/main/res/drawable/ic_home.xml
  presentation/src/main/res/drawable/ic_rank_label.xml
  presentation/src/main/res/drawable/shape_thumb.xml
  presentation/src/main/res/layout/activity_promise_history.xml
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/layout/layout_history_progress.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#197 약속 상세 정보 관련, Notification, ShakeDialog 문제 및 버그 해결
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/model/PromiseData.kt
  presentation/src/main/kotlin/com/woory/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/ShakeDeviceFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/res/layout/bottomsheet_gaming.xml
  presentation/src/main/res/layout/dialog_fragment_shake_device.xml
  presentation/src/main/res/layout/fragment_gaming.xml
Labels: 🐞 버그

#200 약속 히스토리 화면 리팩토링
  build.gradle.kts
  data/src/main/kotlin/com/woory/data/model/MagneticInfoModel.kt
  data/src/main/kotlin/com/woory/data/model/PromiseHistoryModel.kt
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/DatabaseDataSource.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  database/src/main/kotlin/com/woory/database/PromiseAlarmDao.kt
  database/src/main/kotlin/com/woory/database/datasource/DefaultDatabaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/mapper/MagneticDataMapper.kt
  firebase/src/main/kotlin/com/woory/firebase/model/MagneticInfoDocument.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/woory/presentation/background/alarm/AlarmFunctions.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/binding/ViewBinding.kt
  presentation/src/main/kotlin/com/woory/presentation/model/MagneticInfo.kt
  presentation/src/main/kotlin/com/woory/presentation/model/PromiseAlarm.kt
  presentation/src/main/kotlin/com/woory/presentation/model/PromiseHistory.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/history/PromiseHistoryMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/model/mapper/magnetic/MagneticInfoMapper.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/RankBadge.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryAdapter.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/util/TimeUtils.kt
  presentation/src/main/res/drawable/ic_bomb.xml
  presentation/src/main/res/drawable/ic_destination.xml
  presentation/src/main/res/drawable/ic_home.xml
  presentation/src/main/res/drawable/ic_rank_label.xml
  presentation/src/main/res/drawable/shape_thumb.xml
  presentation/src/main/res/layout/activity_promise_history.xml
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/layout/layout_history_progress.xml
  presentation/src/main/res/values/colors.xml
Labels: 🐞 버그, 🔨 기능, 🌟 리팩토링

#201 버그 수정, 왕관 리소스 변경
  presentation/src/main/kotlin/com/woory/presentation/model/exception/CreatingPromiseException.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/locationsearch/LocationSearchResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeDecoration.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/customview/topitemresize/TopItemResizeScrollListener.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/join/ProfileActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/util/ResourceManager.kt
  presentation/src/main/res/drawable/ic_crown.xml
  presentation/src/main/res/layout/dialog_fragment_total_cost.xml
  presentation/src/main/res/layout/item_promise_user.xml
  presentation/src/main/res/values-night/colors.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: 🐞 버그, 🌟 리팩토링

#208 InitialRadius 필드 set 안되는 버그 수정
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/model/MagneticInfoDocument.kt
Labels: 🐞 버그

#210 게임 화면 초기 위치 설정 및 자기장 버그 수정
  data/src/main/kotlin/com/woory/data/util/Const.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/res/layout/fragment_promise_info.xml
Labels: 🐞 버그

#214 약속 히스토리 카드에서 자기장 위치 조정되는 버그 수정, initial radius set 하는 위치 변경
  data/src/main/kotlin/com/woory/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/data/source/FirebaseDataSource.kt
  firebase/src/main/kotlin/com/woory/firebase/datasource/DefaultFirebaseDataSource.kt
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/history/PromiseHistoryAdapter.kt
  presentation/src/main/res/layout/item_promise_history.xml
  presentation/src/main/res/layout/layout_history_progress.xml
Labels: 🐞 버그

#212 DialogFragment 강제 종료 및 게임 결과 화면에서 버그 수정
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultViewModel.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/res/values/strings.xml
Labels: 🐞 버그

#217 대중 교통 조회시 역 끼리의 소요시간만 가져와지는 문제 해결
  network/src/main/kotlin/com/woory/network/DefaultNetworkDataSource.kt
Labels: 🐞 버그

#223 buildSrc, version catalog 적용
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/woory/almostthere/initializer/KakaoSdkInitializer.kt
  app/src/test/kotlin/com/woory/almostthere/ExampleUnitTest.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Configuration.kt
  data/build.gradle.kts
  database/build.gradle.kts
  firebase/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  network/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/woory/presentation/ui/creatingpromise/CreatingPromiseActivity.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gameresult/GameResultActivity.kt
  presentation/src/main/res/layout/fragment_gaming.xml
  settings.gradle.kts
Labels: 🌟 리팩토링

#222 게임 화면 shake 버그 해결 및 비정상적으로 api가 호출되는 버그 수정
  presentation/src/main/kotlin/com/woory/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/presentation/ui/gaming/GamingFragment.kt
Labels: 🐞 버그

#228 코드 리팩토링
  data/src/main/kotlin/com/woory/almostthere/data/model/PromiseHistoryModel.kt
  data/src/main/kotlin/com/woory/almostthere/data/model/UserHpModel.kt
  data/src/main/kotlin/com/woory/almostthere/data/repository/DefaultPromiseRepository.kt
  data/src/main/kotlin/com/woory/almostthere/data/repository/PromiseRepository.kt
  data/src/main/kotlin/com/woory/almostthere/data/source/NetworkDataSource.kt
  network/src/main/kotlin/com/woory/almostthere/network/DefaultNetworkDataSource.kt
  network/src/main/kotlin/com/woory/almostthere/network/model/UserHpDocument.kt
  network/src/main/kotlin/com/woory/almostthere/network/model/mapper/AddedUserHpMapper.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/background/notification/NotificationProvider.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/background/service/PromiseGameService.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/binding/BindingAdapter.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/model/PromiseHistory.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/model/User.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/model/UserHp.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/model/WooryTMapCircle.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/model/mapper/user/AddedUserHpMapper.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/CreatingPromiseFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/CreatingPromiseViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/locationsearch/LocationSearchFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/locationsearch/LocationSearchResultFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/locationsearch/LocationSearchResultViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/creatingpromise/locationsearch/LocationSearchViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/gameresult/GameResultFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/gameresult/SplitMoneyFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/gaming/GamingFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/gaming/GamingViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/history/PromiseHistoryViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/join/CodeState.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/promiseinfo/PromiseInfoFragment.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/ui/promiseinfo/PromiseInfoViewModel.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/util/Exceptions.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/util/InviteCodeUtil.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/util/TimeConverter.kt
  presentation/src/main/kotlin/com/woory/almostthere/presentation/util/ViewUtils.kt
Labels: 🌟 리팩토링
